create-ui:
	yarn create react-app ./web --template typescript --name wild-workout-web-ui

install:
	yarn add react-router-dom @types/react-router-dom

dev:
	yarn start

clean-cache:
	rm -rf node_modules
	rm yarn.lock
	yarn cache clean
	yarn install
